CREATE DATABASE IF NOT EXISTS SEPCAMP;

USE SEPCAMP;

CREATE TABLE IF NOT EXISTS SEPCAMP_USER
(
    USER_ID     INTEGER         NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '用户ID',
    EMAIL       VARCHAR(50)     NOT NULL COMMENT '邮箱',
    NAME        CHAR(12)        NOT NULL COMMENT '真实名字' DEFAULT '',
    STUDENT_ID  CHAR(15)        COMMENT '学号，助教老师不包含该项',
    CLASS_ID    SMALLINT        COMMENT '班级编号，助教老师不包含该项',
    TEAM_ID     INTEGER         COMMENT '所属小队ID，助教老师和尚未加入小队的学生不包含该项',
    USERNAME    VARCHAR(20)     NOT NULL COMMENT '用户名',
    QQNUMBER    VARCHAR(20)     NOT NULL COMMENT 'qq',
    INTERESTS    VARCHAR(1000)     NOT NULL COMMENT '兴趣',
    INTRODUCTION    VARCHAR(1000)     NOT NULL COMMENT '个人介绍',
    PASSWORD    CHARACTER(60)   NOT NULL COMMENT '密码hash',
    PRIORITY    SMALLINT        NOT NULL COMMENT '权限',
    AVATAR      CHARACTER(37)   NOT NULL COMMENT '头像文件名',
    TERM        CHARACTER(5)    NOT NULL COMMENT '学期',
    ENABLED     BOOLEAN         NOT NULL COMMENT '用户是否已经验证'
)
CHARACTER SET = utf8
COMMENT 'sepcamp用户表';

