CREATE DATABASE IF NOT EXISTS SEPCAMP;

USE SEPCAMP;

CREATE TABLE IF NOT EXISTS SEPCAMP_PROJECT
(
    PROJECT_ID      INTEGER             NOT NULL PRIMARY KEY COMMENT '项目ID',
    INTRODUCTION    VARCHAR(1000)       NOT NULL COMMENT '项目简介',
    VISIBLE         SMALLINT            NOT NULL COMMENT '可见范围',
    TERM            CHARACTER(5)        NOT NULL COMMENT '学期'
)
CHARACTER SET = utf8
COMMENT 'sepcamp项目表';