CREATE DATABASE IF NOT EXISTS SEPCAMP;

USE SEPCAMP;

CREATE TABLE IF NOT EXISTS SEPCAMP_TEAM
(
    TEAM_ID     INTEGER         NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '小队ID',
    TEAM_NAME   CHARACTER(20)   NOT NULL COMMENT '小队名字',
    LEADER      INTEGER         NOT NULL COMMENT '队长的User ID' ,
    PROJECT_ID  INTEGER         COMMENT '项目ID',
    TERM        CHARACTER(5)    NOT NULL COMMENT '学期',
    INTRODUCTION    VARCHAR(1000) COMMENT '项目简介'
)
CHARACTER SET = utf8
COMMENT 'sepcamp小队表';