CREATE TABLE SEPCAMP_FUNCTION
(
    FUNCTION_ID     INTEGER         NOT NULL PRIMARY KEY COMMENT '功能ID',
    DESCRIPTION     VARCHAR(1000)   NOT NULL COMMENT '功能描述',
    PROJECT_ID      INTEGER         NOT NULL COMMENT '所属项目',
    FUNCTIONAL_TYPE SMALLINT        NOT NULL COMMENT '功能类型'
)
CHARACTER SET = utf8
COMMENT 'sepcamp功能表'